### ISSUE TITLE
Handle Request Time Out after 10s

### ISSUE THREAD

**Issue by alivalid** [worxid/worx-android#52]
Fatal Exception: java.net.SocketTimeoutException: failed to connect to api.dev.worx.id/103.30.246.130 (port 443) from /10.0.2.16 (port 36584) after 10000ms

https://console.firebase.google.com/project/worx-id/crashlytics/app/android:id.worx.device.client/issues/90fbc972c4533952b2112f9b78d8eaf0?time=last-seven-days&sessionEventKey=6384A26502D200010256CE1E27777B7F_1749480796808988126
https://console.firebase.google.com/project/worx-id/crashlytics/app/android:id.worx.device.client/issues/1538700de198126f9c29dd0228792ed9?time=last-seven-days&sessionEventKey=6382D1B6007B00012B4679CB3CFD7E44_1748969789149151973

Reproduce :
1. Cara Pertama
    - Matikan koneksi internet
    - Buka App Worx
2. Cara Kedua
    - Buka App Worx
    - Matikan Koneksi Internet
    - Swipe to refresh pada tampilan Home Worx
    
 Butuh UI untuk tampilan No Connection/Connection Problem

**Comment by andrea-liu87** [comment]
UI update from designer
https://www.figma.com/file/X6sBV3Ajn1Jjgqf3gecfWY/Worx-Mobile?t=BCM8mh6LtZRzEfcd-0
